/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ShouldIBuyRouteImport } from './routes/should-i-buy'
import { Route as ClosetIndexRouteImport } from './routes/closet.index'
import { Route as ClosetItemIdRouteImport } from './routes/closet.$itemId'
import { Route as FittingRoomIndexRouteImport } from './routes/fitting-room/index'
import { Route as FittingRoomCaptureRouteImport } from './routes/fitting-room/capture'
import { Route as LookOutfitIdRouteImport } from './routes/look.$outfitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ShouldIBuyRoute = ShouldIBuyRouteImport.update({
  id: '/should-i-buy',
  path: '/should-i-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetIndexRoute = ClosetIndexRouteImport.update({
  id: '/closet/',
  path: '/closet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetItemIdRoute = ClosetItemIdRouteImport.update({
  id: '/closet/$itemId',
  path: '/closet/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const FittingRoomIndexRoute = FittingRoomIndexRouteImport.update({
  id: '/fitting-room/',
  path: '/fitting-room/',
  getParentRoute: () => rootRouteImport,
} as any)
const FittingRoomCaptureRoute = FittingRoomCaptureRouteImport.update({
  id: '/fitting-room/capture',
  path: '/fitting-room/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const LookOutfitIdRoute = LookOutfitIdRouteImport.update({
  id: '/look/$outfitId',
  path: '/look/$outfitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ideas': typeof IdeasRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/should-i-buy': typeof ShouldIBuyRoute
  '/closet/$itemId': typeof ClosetItemIdRoute
  '/fitting-room/capture': typeof FittingRoomCaptureRoute
  '/look/$outfitId': typeof LookOutfitIdRoute
  '/closet/': typeof ClosetIndexRoute
  '/fitting-room/': typeof FittingRoomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ideas': typeof IdeasRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/should-i-buy': typeof ShouldIBuyRoute
  '/closet/$itemId': typeof ClosetItemIdRoute
  '/fitting-room/capture': typeof FittingRoomCaptureRoute
  '/look/$outfitId': typeof LookOutfitIdRoute
  '/closet': typeof ClosetIndexRoute
  '/fitting-room': typeof FittingRoomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ideas': typeof IdeasRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/should-i-buy': typeof ShouldIBuyRoute
  '/closet/$itemId': typeof ClosetItemIdRoute
  '/fitting-room/capture': typeof FittingRoomCaptureRoute
  '/look/$outfitId': typeof LookOutfitIdRoute
  '/closet/': typeof ClosetIndexRoute
  '/fitting-room/': typeof FittingRoomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/ideas'
    | '/planner'
    | '/quiz'
    | '/should-i-buy'
    | '/closet/$itemId'
    | '/fitting-room/capture'
    | '/look/$outfitId'
    | '/closet/'
    | '/fitting-room/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/ideas'
    | '/planner'
    | '/quiz'
    | '/should-i-buy'
    | '/closet/$itemId'
    | '/fitting-room/capture'
    | '/look/$outfitId'
    | '/closet'
    | '/fitting-room'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/ideas'
    | '/planner'
    | '/quiz'
    | '/should-i-buy'
    | '/closet/$itemId'
    | '/fitting-room/capture'
    | '/look/$outfitId'
    | '/closet/'
    | '/fitting-room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  IdeasRoute: typeof IdeasRoute
  PlannerRoute: typeof PlannerRoute
  QuizRoute: typeof QuizRoute
  ShouldIBuyRoute: typeof ShouldIBuyRoute
  ClosetItemIdRoute: typeof ClosetItemIdRoute
  FittingRoomCaptureRoute: typeof FittingRoomCaptureRoute
  LookOutfitIdRoute: typeof LookOutfitIdRoute
  ClosetIndexRoute: typeof ClosetIndexRoute
  FittingRoomIndexRoute: typeof FittingRoomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/should-i-buy': {
      id: '/should-i-buy'
      path: '/should-i-buy'
      fullPath: '/should-i-buy'
      preLoaderRoute: typeof ShouldIBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet/': {
      id: '/closet/'
      path: '/closet'
      fullPath: '/closet/'
      preLoaderRoute: typeof ClosetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet/$itemId': {
      id: '/closet/$itemId'
      path: '/closet/$itemId'
      fullPath: '/closet/$itemId'
      preLoaderRoute: typeof ClosetItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitting-room/': {
      id: '/fitting-room/'
      path: '/fitting-room'
      fullPath: '/fitting-room/'
      preLoaderRoute: typeof FittingRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitting-room/capture': {
      id: '/fitting-room/capture'
      path: '/fitting-room/capture'
      fullPath: '/fitting-room/capture'
      preLoaderRoute: typeof FittingRoomCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/look/$outfitId': {
      id: '/look/$outfitId'
      path: '/look/$outfitId'
      fullPath: '/look/$outfitId'
      preLoaderRoute: typeof LookOutfitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  IdeasRoute: IdeasRoute,
  PlannerRoute: PlannerRoute,
  QuizRoute: QuizRoute,
  ShouldIBuyRoute: ShouldIBuyRoute,
  ClosetItemIdRoute: ClosetItemIdRoute,
  FittingRoomCaptureRoute: FittingRoomCaptureRoute,
  LookOutfitIdRoute: LookOutfitIdRoute,
  ClosetIndexRoute: ClosetIndexRoute,
  FittingRoomIndexRoute: FittingRoomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
